name: PassMac
options:
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    PRODUCT_NAME: PassMac
targets:
  PassMac:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources/app_macos
      - path: Sources/shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pass.desktop
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: PassMac
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-lsqlite3"
schemes:
  PassMac:
    build:
      targets:
        PassMac: all
