import path from "node:path";
import { readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import esbuild from "esbuild";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(scriptDir, "..");
const outDir = path.join(rootDir, "dist");
const watchMode = process.argv.includes("--watch");
const appsDir = path.resolve(rootDir, "..");

const PLATFORM_MANIFESTS = [
  {
    path: path.join(rootDir, "manifest.json"),
    // Shared template is also the Safari Web Extension resource source.
    // Keep the product name browser-neutral so Safari does not show "Chrome".
    name: "Pass",
    description:
      "Password manager extension with device name, domain alias groups, autofill, and encrypted local vault.",
  },
  {
    path: path.join(appsDir, "extension_chrome", "manifest.json"),
    name: "Pass - Chrome Extension",
    description:
      "Password manager extension for Chrome with device name, domain alias groups, autofill, and encrypted local vault.",
  },
  {
    path: path.join(appsDir, "extension_firefox", "manifest.json"),
    name: "Pass - Firefox Extension",
    description:
      "Password manager extension for Firefox with device name, domain alias groups, autofill, and encrypted local vault.",
  },
];

async function syncExtensionVersion() {
  const packageJson = JSON.parse(await readFile(path.join(rootDir, "package.json"), "utf8"));
  const version = String(packageJson.version || "").trim();
  if (!/^\d+\.\d+\.\d+/.test(version)) {
    throw new Error(`Invalid package.json version: ${packageJson.version}`);
  }

  const versionModule = `// Generated by scripts/build.mjs from package.json — do not edit by hand.
export const PASS_EXTENSION_VERSION = ${JSON.stringify(version)};
`;
  await writeFile(path.join(rootDir, "extension_version.js"), versionModule, "utf8");

  for (const platform of PLATFORM_MANIFESTS) {
    const manifest = JSON.parse(await readFile(platform.path, "utf8"));
    let changed = false;
    if (manifest.version !== version) {
      manifest.version = version;
      changed = true;
    }
    if (platform.name && manifest.name !== platform.name) {
      manifest.name = platform.name;
      changed = true;
    }
    if (platform.description && manifest.description !== platform.description) {
      manifest.description = platform.description;
      changed = true;
    }
    if (changed) {
      await writeFile(platform.path, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
    }
  }

  return version;
}

const buildOptions = {
  entryPoints: {
    popup: path.join(rootDir, "popup.js"),
    options: path.join(rootDir, "options.js"),
    background: path.join(rootDir, "background.js"),
    content: path.join(rootDir, "content.js"),
    webauthn_injected: path.join(rootDir, "webauthn_injected.js"),
  },
  outdir: outDir,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["safari17", "firefox128", "chrome120"],
  logLevel: "info",
  legalComments: "none",
  sourcemap: false,
};

async function main() {
  const version = await syncExtensionVersion();
  await rm(outDir, { recursive: true, force: true });

  if (watchMode) {
    const context = await esbuild.context(buildOptions);
    await context.watch();
    console.log(`Watching extension bundles in dist/ (version ${version}) ...`);
    return;
  }

  await esbuild.build(buildOptions);
  console.log(`Built shared extension bundles to dist/ (version ${version}).`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
